name: Deploy Frontend Cloud Storage

on:
  push:
    branches:
      - master

# adapted form https://github.com/google-github-actions/deploy-cloudrun/blob/main/.github/workflows/example-workflow.yaml
env:
  BUCKET: ${{ secrets.GCP_BUCKET }}
  SA_KEY: ${{ secrets.GCP_SA_KEY }}
  REGION: asia-northeast1
  VITE_API_KEY: ${{ secrets.VITE_API_KEY}}
  VITE_AUTH_DOMAIN: ${{ secrets.VITE_AUTH_DOMAIN}}
  VITE_API_ENDPOINT: ${{ secrets.VITE_API_ENDPOINT}}

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-yarn
        with:
          path: "**/node_modules"
          key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-

      - name: Install deps
        if: steps.cache-yarn.outputs.cache-hit != 'true'
        run: yarn

      - name: Build
        run: yarn build

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ env.SA_KEY }}
          export_default_credentials: true

      - name: upload-files
        run: |
          gsutil --quiet -m -d cp -a public-read -R dist/* ${{ env.BUCKET }}

      # TODO: setup Cache-Control

      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              username: 'deploy-frontend',
              icon_emoji: ':vue:',
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `Deploy frontend done in ${process.env.AS_TOOK} :vue: \n ${{ secrets.DEPLOY_WEB_URL }}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
