name: Test backend

on: [push]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: "postgresql://tsukiyo:github@localhost/test"
  ADMIN_CONFIG: "{}"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    services:
      db:
        image: postgres:12
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: tsukiyo
          POSTGRES_PASSWORD: github
          POSTGRES_INITDB_ARGS: --encoding=UTF-8
          POSTGRES_DB: test

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: |
          cargo check --verbose

      - name: Run tests
        run: cargo test --verbose

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          icon_emoji: ":actix:"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
