name: Test frontend

on:
  push:
    branches-ignore:
      - master

env:
  HUSKY: 0

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-yarn
        with:
          path: "**/node_modules"
          key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-

      - name: Install deps
        if: steps.cache-yarn.outputs.cache-hit != 'true'
        run: yarn

      - name: Test Lint
        run: yarn lint

      - name: Test Jest
        run: yarn test:unit

      # TODO: fix and e2e/type tests

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          icon_emoji: ":vue:"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
