name: Test backend

on: [push]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: "postgresql://tsukiyo:github@db/test"

jobs:
  test-backend:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:12
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: tsukiyo
          POSTGRES_PASSWORD: github
          POSTGRES_INITDB_ARGS: --encoding=UTF-8
          POSTGRES_DB: test

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
