name: Test frontend

on: [pull_request]

env:
  HUSKY: 0

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-yarn
        with:
          path: "**/node_modules"
          key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-

      - name: Install deps
        if: steps.cache-yarn.outputs.cache-hit != 'true'
        run: yarn

      - name: Test Lint
        run: yarn lint

      - name: Test Build
        uses: preactjs/compressed-size-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          pattern: "./dist/**/*"
          minimum-change-threshold: 200
          strip-hash: "\\.(\\w+)\\..+?$$"
          cwd: ./frontend
        env:
          CHUNK_NAME: full
